### ISSUE TITLE
Game path does not appear to save after exiting/reopening the program.

### ISSUE THREAD

**Issue by paroxysmal** [clementgallet/SWD2Randomizer#1]

**Comment by paroxysmal** [comment]
this is if the game path is not the steam default?

**Comment by paroxysmal** [comment]
also, please add a "done!" when the randomizer is done with the restore.

**Comment by clementgallet** [comment]
Game path is now saved inside settings (2b0cff28993d5357cf5282c40019dc7c91b7c92d)

**Comment by clementgallet** [comment]
Log message says when restoring is done (a7d52a37d0f16f6c2da51b2673d349bbfda3ecc1).
