### ISSUE TITLE
Logic: S3802098 appears unsolvable

### ISSUE THREAD

**Issue by paroxysmal** [clementgallet/SWD2Randomizer#13]
You need the fire pickaxe to get the fire pickaxe. Let me know if I'm missing something.

Thanks

**Comment by clementgallet** [comment]
You don't need the fire pickaxe to finish the game (you can skip the first Device), and I included this possibility in Speedrun mode. Should I change it by always letting people completing the game as intended ?

**Comment by paroxysmal** [comment]
How do you get the swamp machine without the pressure bomb in this seed

**Comment by paroxysmal** [comment]
No leave that logic as is. I play speed run mode for the challenge not for the sake of quickest end boss fight so that was my fault in forgetting that. But I’d still like to know what I’m missing to complete the seed if possible.

**Comment by paroxysmal** [comment]
so upon looking at my reveal file it shows that the pressure bomb is in the airjet upgrade spot. when i go down to get to vectron fen will not talk to allow entry to vectron. the other quest is at the lava battle and i need the ignition axe to get to there. I am not sure how to proceed or get fen to start dialogue to get to vectron to proceed.

**Comment by paroxysmal** [comment]
add S2699404 as another possible seed that seems unsolvable.

**Comment by paroxysmal** [comment]
in looking through your code for the logic it seems to only take into account the upgrades and not the quest progression roadblocks. I am not sure how much you want to update this project anymore but I think that may be why I am having some issues with completing some of the seeds. it is also possible you took account for the quest progression road blocks at some other place in the code that i have not looked at yet

**Comment by clementgallet** [comment]
I'm very sorry, no I did take into account progression markers in the logic, I didn't know it could close paths.

**Comment by clementgallet** [comment]
Fixed the logic, you need to destroy the first generator before accessing Vectron.
