### ISSUE TITLE
103% yarrow completion??

### ISSUE THREAD

**Issue by Traehgniw** [clementgallet/SWD2Randomizer#15]
Exactly what it says on the tin, I have 103% Yarrow completion. I also don't have 100% West Desert completion despite there being no secrets left there. 

![20190206160856_1](https://user-images.githubusercontent.com/42482668/52318505-aa422c80-2a29-11e9-92a0-87b61043c55d.jpg)

**Comment by clementgallet** [comment]
I guess upgrades don't have all the same percentage value. Not sure I can fix that, and it doesn't seem important to fix.
