### ISSUE TITLE
Talking to Rosie closes the hookshot door [POTENTIAL SOFTLOCK]

### ISSUE THREAD

**Issue by Traehgniw** [clementgallet/SWD2Randomizer#17]
The door correctly starts open, but after talking to Rosie it closes. Talking to Rosie again does not open it; neither does going to El Machino and back, or exiting the game entirely and starting it again.

**Comment by clementgallet** [comment]
Fixed the hook cave door.
I also opened the front door, because we may need to enter from Yarrow shortcut
