### ISSUE TITLE
Randomizer can give you access to areas that you cannot leave [softlock]

### ISSUE THREAD

**Issue by Traehgniw** [clementgallet/SWD2Randomizer#18]
I got the Ignition Axe station below the wall, and completed the boss fight, but it was Jackhammer and upgrade stations are checkpoints. I don't have Ignition Axe and the door is still shut, so I am softlocked. (I have Jetpack and thought progression was Ignition Axe -> Fire Temple, and all other progression options were behind things that would take a really long time to mine.)

The fix for this is to have a teleportation method that can be used right from the start of the game and is not turned off by caves, that either sends you to cave entrance or to some out-of-the-way area where it is always possible to get to Town from, such as the starting ledge or Temple of Guidance upper levels.

By sending you to either Cave Entrance or some out-of-the-way location, it does not compete with Portal of Pardon, much like how Ori 1 alt-R does not compete with the teleport system.

Alternatively, you could do it like Ori 2 rando and start the player with Portal of Pardon permanently socketed and change it to not turn off in caves.

**Comment by clementgallet** [comment]
In this case, you can return to main menu and load your save, it will bring you back to the entrance I think.

**Comment by Traehgniw** [comment]
Okay, so it _did_ bring me back to the entrance, so unless Jackhammer was progression it wasn't a softlock; the door was open, the boss battle unfought, and Dorothy didn't have a jackhammer. 

Still, some method of returning to exit or something without losing all your progress would be preferable.

**Comment by clementgallet** [comment]
That would be complicated to do without modifying the game code unfortunately.
