### ISSUE TITLE
Possible softlock?

### ISSUE THREAD

**Issue by Traehgniw** [clementgallet/SWD2Randomizer#21]
I generated a seed with Casual turned on and I _think_, from both playing it and reading the spoiler, that it wants me to go to Vectron to get the jetpack and everything else is locked behind that - but Fen refuses to go in the teleporter because there's "other stuff to do".

Seed is CIARU9133441 casual all checkboxes ticked.

**Comment by clementgallet** [comment]
Oh, yeah, Vectron access is an issue. There is also the issue that when you finish vectron and are in the jetpack room, you cannot leave it unless by climbing up (S+Q doesn't do anything), so if you don't have the right item, you are stuck.

I think I will modify the layout of the Vectron entrance room to give you access to the item right away.

**Comment by clementgallet** [comment]
Removed Vectron in dfa51a31def6de09892ef9a626e91b12ab237197 . Upgrade can be accessed with pressure bomb.
