### ISSUE TITLE
Jackhammer too early.

### ISSUE THREAD

**Issue by paroxysmal** [clementgallet/SWD2Randomizer#3]
When you get the jackhammer too early it breaks the tutorial phase of the game. the fight with the first boss doesnt' happen and you do not get your map until you talk to Fen after vectron. This doesn't inherently break the game you are running and i suppose it could add some more dynamic to it. I am not sure exactly what needs to happen prior to getting the jackhammer for it to not break the tutorial phase.

This may not be fixable. If so please close the issue.

**Comment by clementgallet** [comment]
The first boss is broken from the moment you escape Temple of Guidance through Yarrow using double jump. He doesn't hold any upgrade and does not softlock the game, so I guess we are fine?
