### ISSUE TITLE
Hook upgrade sometimes unreachable.

### ISSUE THREAD

**Issue by paroxysmal** [clementgallet/SWD2Randomizer#4]
On some seeds when you first enter the shiners camp the door is already open to the town and the quest is not available for the lady to open the gate to the hook cave thereby not letting you get the hook cave upgrade on that seed. 

These seeds can be completable, however, the logic needs to make sure that there isn't a needed upgrade in the hook cave.

**Comment by paroxysmal** [comment]
This appears to happen when you get the jackhammer before doing the questline. On these seeds you may have to delete your save and create a new game and avoid the jackhammer powerup until you have fought zen at the beginning temple. Usually this happens to me when I get the secret blueprint at the start and its the jackhammer before I go to the beginners temple.  I am unsure if the logic is affected if you do the temple and then immediately get the jackhammer upgrade right afterwards. Additionally, if you get the jackhammer before doing the starting temple you will not have a map. Prior to the current release you could get the map by completing the fight event in the lava temple but you would have to play the game up until that point without a map or being able to toggle map upgrades like the one that identifies ore locations.

**Comment by clementgallet** [comment]
I changed the layout so that the door to hook cave is always opened.
