### ISSUE TITLE
Grenade doesn't give a water bar

### ISSUE THREAD

**Issue by Traehgniw** [clementgallet/SWD2Randomizer#6]
if Grenade is in burster's station, it doesn't give you a water bar, so you can't fire it, so you're stuck. 

even if you could alt-R or something to go back to town, you'd still be stuck unless you could buy the tier 1 water tank as you can't fire any grenades and so can't continue through Red Rock Passage.

...my very first seed had grenade in Burster's Station and it sucked.

**Comment by clementgallet** [comment]
Seeds are chosen so that you can always complete the game. Did you choose "Speedrun" mode? If so, you are supposed to know that you can use double jump to enter Yarrow from the Temple of Guidance.

**Comment by clementgallet** [comment]
Also, the fact that only pressure bombs give water is hardcoded in the game, I can't do much about it, except by extensive research to decompile and patch the code (I tried a bit and failed).

**Comment by Traehgniw** [comment]
In which case I would like to report an issue that casual seed gen does not work and it silently gens a speedrun seed instead.

**Comment by Traehgniw** [comment]
...hmm, would it be easier to have a water bar given at the very start? That'd completely bypass the need to make anything give a water bar.
Then, you could allow for such things as casual Burster's Station grenade.

**Comment by clementgallet** [comment]
Again, that doesn't seem to be possible, except by giving pressure bomb too :(

**Comment by clementgallet** [comment]
Maybe asking the devs to patch the game by giving water for any item using water :)

**Comment by paroxysmal** [comment]
Most items that use water may give you a bit of initial water, like the jetpack but soon quit working. Most of the water related issues I have had after immediately getting an upgrade is to reload the screen either by moving one screen away or returning to town and then returning. That updates your water meter and allows usability.

**Comment by Traehgniw** [comment]
I couldn't move one screen away or return to town AND keep the upgrade, I was in the pressure bomb cave and couldn't get out.

**Comment by paroxysmal** [comment]
yea, there are certain upgrade locations you may have to skip until later. there are a couple ways to get out of the pressure bomb cave. the airjet with ramjet vigor will destroy the block and allow you out, and deathplosions you can lure the upper beetle down to the platform where the rock normally drops allowing you to shoot the sand wall with the pressure bomb, then have trigger the beetle to dash to the right towards that sand block and kill it with the pickaxe as its a bit off the edge towards that sand block and the deathplosion should destroy that sand block if you do it right, though it can be frustratingly hard it is doable. 

overall the pressure bomb is a very limiting factor so if you can get it you definitely want to it will make your run significantly easier.

**Comment by Traehgniw** [comment]
to clarify: this was a casual seed.
due to a combination of this being causal difficulty, Davy's blueprints not being in the randomizer items pool, artifacts not being in the upgrade pool, and a lack of return to start/return to start of cave functionality, this seed would have required escaping the tutorial right at the beginning of the game to get some other upgrade somewhere. 
i can't tutorial escape.

**Comment by paroxysmal** [comment]
whats your seed# for it? I'll play through it and see how doable it is from a non-speedrun standpoint to see what we may be missing

**Comment by Traehgniw** [comment]
I no longer have the seed for it, and in fact even if I did the underlying issue of the logic assuming that the tutorial escape was always possible and done was fixed a version or two ago.

**Comment by paroxysmal** [comment]
oh, ok, i wasn't aware that the issue had been resolved. want to close your issue then?

**Comment by Traehgniw** [comment]
Grenade giving a water bar at the time would still be a really big improvement, allowing for casual to actually have path divergences on the second upgrade podium.

**Comment by paroxysmal** [comment]
you mean after you get pressure bomb and then grenade? if you do the upgrade path you should have water bar already by the time you get grenade. if you get grenade without pressure bomb you can't throw a grenade until you get the pressure bomb.

**Comment by Traehgniw** [comment]
Oh, grenade is just strictly a pressure bomb upgrade? somehow i was thinking that the randomizer would separate them a bit

**Comment by paroxysmal** [comment]
yep, need pressure bomb to use grenade, need pressure bomb and grenade to use triple grenade
although i was thinking last night when i was doing a playthrough when i got the pressure bomb from an upgrade station i got a full water tank, however, when ive gotten items that need water from a blueprint spot they work a few times then stop working until you move a screen away @clementgallet

**Comment by clementgallet** [comment]
I don't think I can fix that, it's part of the core engine.
