### ISSUE TITLE
Never recognizes a seed string

### ISSUE THREAD

**Issue by Traehgniw** [clementgallet/SWD2Randomizer#9]
No matter what I put in the seed area it just pops up a 'seed string is unrecognized' error. Only way I can play is by leaving it blank.

**Comment by clementgallet** [comment]
Is it because you are only setting the integer part of the seed and not the prefix letter? In any case, the log message prints the entire seed instead of the integer part only to avoid confusion (10b5c312fcd4f5091dc3a913c37b42d5339466a8)

**Comment by paroxysmal** [comment]
@Traehgniw it appears that there are only a certain number of allowable seeds. If you are putting in a random number its probably not going to work based on my attempts to do similar. There is just not that much randomization with it as the logic needs to allow you a chance to win.
